### ISSUE TITLE
Добавление CommandHandler'а

### ISSUE THREAD

**Issue by HateMe02** [iris2iris/iris-vk-api#3]
![image](https://user-images.githubusercontent.com/64659298/97304033-6fdd7c00-1818-11eb-8ed2-03bd16e01124.png)Как в питоне

**Comment by iris2iris** [comment]
✅ Выполнено

https://github.com/iris2iris/iris-vk-api/commit/234f68e2fac71dbefc50d8536bd4dec4240f2056
